services:
  android-emulator:
    build: .
    privileged: true
    environment:
      - EMULATOR_MEMORY=8192  # Memory in MB
      - EMULATOR_CORES=4      # Number of CPU cores
    volumes:
      - ./output:/output
